# Generated by Django 5.1.1 on 2024-10-08 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('maquina', 'Máquina'), ('libre', 'Libre')], max_length=50)),
                ('img_exercise', models.ImageField(upload_to='exercises/')),
                ('description', models.TextField(max_length=600)),
                ('sets', models.IntegerField(default=4)),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.categories')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weights', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('id_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to='api.exercises')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordsWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weights', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('note', models.TextField(max_length=500)),
                ('repetitions', models.IntegerField()),
                ('intensity', models.CharField(max_length=50)),
                ('id_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_weights', to='api.exercises')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_weights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='api.exercises')),
                ('id_routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='api.routines')),
            ],
        ),
    ]
