# Generated by Django 5.1.1 on 2024-10-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_routines_day_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routines',
            name='day_index',
        ),
        migrations.AddField(
            model_name='routines',
            name='day',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=9),
        ),
    ]
