# Generated by Django 5.1.1 on 2024-11-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routines',
            options={'permissions': [('view_routine', 'Can view routine'), ('change_routine', 'Can change routine'), ('delete_routine', 'Can delete routine')]},
        ),
        migrations.RenameField(
            model_name='exerciseshistory',
            old_name='id_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='recordsweights',
            old_name='id_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='routines',
            old_name='id_user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='exercises',
            name='id_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.categories'),
        ),
    ]
