# Generated by Django 5.1.1 on 2024-11-28 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='-', max_length=144),
        ),
    ]
